import {
  Users,
  Code,
  Database,
  Globe,
  Shield,
  Rocket,
  Zap,
  Cpu,
  Settings,
  TestTube,
  Smartphone,
  Cloud,
  Lock,
} from "lucide-react"
import type { UserType } from "@/types/user-type"
import type { ProjectType } from "@/types/project-type"
import type { Testimonial } from "@/types/testimonial-type"

const testimonials: Testimonial[] = [
  {
    name: 'Alyx Smeal',
    designation: 'Business Analyst',
    company: 'Fusion Medical Staffing',
    src: 'https://media.licdn.com/dms/image/v2/D5603AQGnxoXXM7l8Gg/profile-displayphoto-crop_800_800/B56Zr_k4OXLMAM-/0/1765224449533?e=1790812800&v=beta&t=jrv0_jHc6LHDEW2FZJ3vHGNsqTJ08_ktNu4GYQeR75M',
    quote: `Dan's ability to explain technical concepts to non-technical stakeholders with patience and clarity is unmatched, fostering collaboration and understanding without a hint of superiority. Recently, Dan identified a new CMS for our Tech stack. It will revolutionize our content management, making it more user-friendly and cost-effective. Dan's diligence in researching, involving stakeholders, and demonstrating the product reflects his commitment to finding the best solutions for our team. As a Tech Lead, Dan is a mentor and encourages team members to explore and learn independently, nurturing a culture of growth and empowerment. Above all, Dan's hard work, caring nature, and dedication made him an invaluable member of our team. I don’t know what we would do without Dan here at Fusion.`
  },
  {
    name: 'Emily Slattery',
    designation: 'Product Designer',
    company: 'Fusion Medical Staffing',
    src: 'https://media.licdn.com/dms/image/v2/D5603AQH2vkgzHX7Gzw/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1661356870268?e=2147483647&v=beta&t=U6_311eUAEvyTKqzeLQTSCT3GqD8ycCqBqlcSk0E7Zc',
    quote: `Dan Vigil is a rockstar! Honestly, I don't know what our team would do without his immense skill, vast knowledge, and go-getter spirit. He's willing to dig into the research, take charge, and put in the extra hours when necessary. He did just that when he found a more cost-effective and user-friendly solution to our website content management system (CMS) for Fusion Medical Staffing. He pushes himself and his team members to do their best and to always grow and improve. He is a kind mentor and a friendly sounding board. I'm extremely grateful to have him as a coworker and I look forward to continuing to learn from him.`
  },
  {
    name: 'Laura Campos',
    designation: 'Backend Tech Lead',
    company: 'Fusion Medical Staffing',
    src: './laura-campos.jpeg',
    quote: `His personality and willingness to take on new challenges is one of, if not, the best I have ever seen. He has been an excellent support for the PM and a fantastic mentor for his team. His knowledge and dedication have helped get web and other projects through some difficult times. His focus on positive mentorship has helped repair some damage from poor mentors in the past. I am happy to work with him.`
  },
  {
    name: 'Hanna Littlefield',
    designation: 'Frontend Software Engineer',
    company: 'Greenfield Development',
    src: 'https://hannamlittlefield.github.io/static/media/ProfilePhoto.90ea6907.jpg',
    quote: `I've had the absolute pleasure of having Daniel as my software development mentor for the last two years. When we started working together, I didn't know a single line of code. Since then, he has helped me work my way through Javascript, React, Bootstrap, Agile methodologies, and more. He is a phenomenal mentor who adjusts his teaching and explanations well to any kind of learning preference. He provided clear and concise answers to my questions, and spent as much time as needed with me on different topics and concepts. If I could not wrap my head around something, he would find another way to explain it, or find resources to aid in my learning. He supplied me with a plethora of learning materials geared towards my preference of learning style- and spent time peer programming with me and focusing on topics I was struggling with, or had a passion to learn. He worked with me to define a capstone project that piqued my interest, and assisted in moving the project along. When I was frustrated or felt defeated, he always had the perfect approach to setting me back on track and in the right mindset. He is constantly encouraging and patient, and has dedicated a vast amount of time and resources on my learning adventure. He celebrated wholeheartedly each and every one of my 'win's with me - whether it was completing a major certificate, solving a difficult problem, finishing a project, or landing my first job. With his tutelage, after two years of learning, I accepted a Junior Developer job at a phenomenal company. Even though I'm now a full-time developer, Daniel is still there as a resource for me to reach out to when I am stuck on a problem, or need some words of advice. I would highly recommend Daniel as a mentor, and I vastly owe my new career in software development to his mentoring and guidance!`
  }
]

const projects: ProjectType[] = [
  {
    id: 1,
    title: "GreenField Development Web Platform",
    shortTitle: "GreenField",
    description: "A SaaS web appication",
    detailedDescription:
      "A SaaS cooperative company specializing in building scalable web applications and mentoring self-taught developers.",
    technologies: ["NextJS", "Tailwind CSS", "shadcn/ui", "Vercel"],
    type: "SAAS_PLATFORM",
    status: "ACTIVE",
    icon: Users,
    color: "cyan",
    year: "2022",
    duration: "ongoing",
    team: "2 developers",
    role: "Founder, Tech Lead & Architect",
    challenges: [
      "Building a scalable architecture",
      "Mentoring self-taught developers",
      "Project mentoring with agile methodologies",
      "Ensuring high availability and performance",
    ],
    achievements: ["10 successful projects delivered", "100% client satisfaction", "98% on-time delivery rate"],
    links: {
      live: "https://greenervigil.dev",
      github: "https://github.com/greenervigil/next-portfolio",
    },
  },
  {
    id: 2,
    title: "Learning Portrait API & Database Redesign",
    shortTitle: "Microservices",
    description: "Enterprise microservices architecture",
    detailedDescription:
      "Redesigned a complex microservices architecture for an enterprise application, focusing on scalability, performance, and maintainability. Implemented a zero-downtime migration strategy and optimized data consistency across services.",
    technologies: ["NextJS", "Swagger", "PostgreSQL", "Apollo Client", "Docker", "Heroku"],
    type: "ENTERPRISE_SOLUTION",
    status: "PRODUCTION",
    icon: Shield,
    color: "orange",
    year: "2024",
    duration: "12 months",
    team: "2 developers",
    role: "Tech Lead & Architect",
    challenges: [
      "Zero-downtime migration strategy",
      "Data consistency across services",
      "Performance optimization at scale",
      "Authentication and authorization complexities",
    ],
    achievements: [
      "Reduced API response time by 50%",
      "Improved data consistency across services",
      "Achieved 99.99% uptime during migration",
    ],
    links: {},
  },
  {
    id: 3,
    title: "Learning Portrait Frontend Gradebook",
    shortTitle: "Competency Gradebook",
    description: "Real-time collaboration platform",
    detailedDescription:
      "Developed a real-time collaboration platform for educational institutions, enabling teachers and students to interact seamlessly",
    technologies: ["NextJS", "TypeScript", "Material UI", "GraphQL", "Storybook", "Auth0", "Vercel"],
    type: "SAAS_PLATFORM",
    status: "COMPLETED",
    icon: Rocket,
    color: "cyan",
    year: "2024",
    duration: "12 months",
    team: "1 developers",
    role: "Full-Stack Tech Lead",
    challenges: ["Real-time data synchronization", "Scalability for large user base", "Cross-platform compatibility"],
    achievements: [
      "Delivered fully featured demo application",
      "Achieved 99.9% real-time sync accuracy",
      "Reduced load time by 40%",
    ],
    links: {},
  },
  {
    id: 4,
    title: "Ultra Crew Mobile Application",
    shortTitle: "Long distance running assistant",
    description: "Crew assistant for long distance running",
    detailedDescription:
      "Developed a comprehensive mobile application for long-distance runners, providing real-time performance tracking, personalized training plans, and community features.",
    technologies: ["React Native", "Supabase", "Expo", "Stripe"],
    type: "MOBILE_APP",
    status: "ACTIVE",
    icon: Smartphone,
    color: "orange",
    year: "2024",
    duration: "8 months",
    team: "2 developers",
    role: "Mobile Lead Architect",
    challenges: [
      "Real-time performance tracking",
      "Personalized training algorithms",
      "Community engagement features",
    ],
    achievements: ["Launched to App Store and Google Play"],
    links: {
      demo: "https://ultracrew.app",
    },
  },
  {
    id: 5,
    title: "Ultra Crew Web Application",
    shortTitle: "Ultra Crew Web",
    description: "Web platform for long distance running",
    detailedDescription:
      "Built a feature-rich web application for long-distance runners, offering advanced search, AR product visualization, secure payments, and personalized recommendations.",
    technologies: ["NextJS", "Supabase", "Tailwind CSS", "Stripe", "Vercel"],
    type: "WEB_APP",
    status: "ACTIVE",
    icon: Cpu,
    color: "cyan",
    year: "2024",
    duration: "8 months",
    team: "2 developers",
    role: "Mobile Lead Developer",
    challenges: ["AR integration complexity", "Payment security implementation", "Performance on low-end devices"],
    achievements: ["50K+ downloads in first month", "4.8/5 app store rating", "30% increase in mobile sales"],
    links: {
      live: "https://ultracrew.app",
    },
  },
  {
    id: 6,
    title: "C&M Mechanical Services Customer web application",
    shortTitle: "C&M Mechanical Services",
    description: "Redesigned customer web application",
    detailedDescription:
      "Redesigned and implemented a customer-facing web application for C&M Mechanical Services, focusing on user experience, performance, and scalability. Integrated CI/CD pipelines for automated deployments and monitoring.",
    technologies: ["NextJS", "Cognito Forms", "Tailwind CSS", "Vercel"],
    type: "WEB_APP",
    status: "PRODUCTION",
    icon: Settings,
    color: "orange",
    year: "2021",
    duration: "4 months",
    team: "1 developers",
    role: "Architect & Developer",
    challenges: ["Legacy system integration", "User experience improvements", "CI/CD pipeline setup"],
    achievements: [
      "Improved user satisfaction by 40%",
      "Reduced page load time by 60%",
      "Achieved 99.9% uptime with automated monitoring",
      "Successfully migrated legacy data without downtime",
      "Implemented CI/CD pipeline for automated deployments",
    ],
    links: {
      live: "https://cmmechanicalhvac.com",
    },
  },
  {
    id: 7,
    title: "Animation Product Calculator",
    shortTitle: "Animation Calculator",
    description: "Product calculator for creative animations",
    detailedDescription:
      "Developed a product calculator for creative animations, allowing users to estimate costs based on various parameters and generate detailed reports.",
    technologies: ["Wordpress", "HTML", "Sass", "CSS", "PHP"],
    type: "ANIMATION_TOOL",
    status: "COMPLETED",
    icon: Lock,
    color: "cyan",
    year: "2019",
    duration: "3 months",
    team: "1 developers",
    role: "Developer",
    challenges: [
      "Complex cost estimation algorithms",
      "User-friendly interface design",
      "Integration with existing systems",
    ],
    achievements: ["On-time delivery", "High user satisfaction", "Improved cost estimation accuracy by 30%"],
    links: {
      live: "https://cs.cengage.com/animation-calculator/",
    },
  },
  {
    id: 8,
    title: "Express Animations",
    shortTitle: "Wordpress page",
    description: "Wordpress page for Express Animations",
    detailedDescription:
      "Developed a Wordpress page for Express Animations, focusing on performance optimization, SEO, and user engagement. Implemented custom themes and plugins to enhance functionality.",
    technologies: ["Wordpress", "HTML", "CSS", "Sass", "PHP"],
    type: "WORDPRESS_PAGE",
    status: "COMPLETED",
    icon: Cloud,
    color: "orange",
    year: "2019",
    duration: "1 months",
    team: "1 developers",
    role: "Developer",
    challenges: ["Performance optimization", "SEO enhancements", "Custom theme development"],
    achievements: [
      "Improved page load time by 50%",
      "Increased organic traffic by 40%",
      "Achieved top rankings for target keywords",
    ],
    links: {
      live: "https://cs.cengage.com/capabilities/media-design/animation/express-animations/",
    },
  },
  {
    id: 9,
    title: "Big Ideas Math Marketing Campaign",
    shortTitle: "Marketing Campaign",
    description: "Marketing campaign for Big Ideas Math",
    detailedDescription:
      "Developed a comprehensive marketing campaign for Big Ideas Math, including social media strategies, content creation, and performance analytics. Focused on increasing brand awareness and engagement.",
    technologies: ["HTML", "CSS", "Bootstrap", "JavaScript"],
    type: "MARKETING_CAMPAIGN",
    status: "PRODUCTION",
    icon: Globe,
    color: "cyan",
    year: "2019",
    duration: "2 months",
    team: "1 developers",
    role: "Developer",
    challenges: ["Brand awareness strategies", "Content creation for diverse platforms", "Performance analytics"],
    achievements: ["Achieved 200K+ impressions", "Increased engagement by 150%", "Generated 5K+ leads"],
    links: {
      live: "https://ngl.cengage.com/assets/html/bigIdeas/index.htm",
    },
  },
  {
    id: 10,
    title: "NGL K-12 Marketing Campaign",
    shortTitle: "NGL K-12 Campaign",
    description: "National Geographic Learning K-12 marketing campaign",
    detailedDescription:
      "Developed a national marketing campaign for National Geographic Learning K-12, focusing on interactive content, user engagement, and performance tracking. Implemented automated testing frameworks to ensure quality and reliability.",
    technologies: ["HTML", "CSS", "Bootstrap", "JavaScript"],
    type: "MARKETING_CAMPAIGN",
    status: "PRODUCTION",
    icon: TestTube,
    color: "orange",
    year: "2018",
    duration: "3 months",
    team: "1 developers",
    role: "Developer",
    challenges: ["Interactive content development", "User engagement strategies", "Automated testing implementation"],
    achievements: ["Achieved 300K+ impressions", "Increased user engagement by 200%", "Generated 10K+ leads"],
    links: {
      live: "https://ngl.cengage.com/assets/html/digitalAccess/index.html",
    },
  },
  {
    id: 11,
    title: "NGL Digital Marketing Campaign",
    shortTitle: "Digital Marketing Campaign",
    description: "National Geographic Learning digital marketing campaign",
    detailedDescription:
      "Developed a digital marketing campaign for National Geographic Learning, focusing on data-driven strategies, real-time analytics, and personalized user experiences. Implemented a robust data pipeline for continuous improvement.",
    technologies: ["HTML", "CSS", "Bootstrap", "JavaScript"],
    type: "DIGITAL_MARKETING_CAMPAIGN",
    status: "PRODUCTION",
    icon: Database,
    color: "cyan",
    year: "2018",
    duration: "3 months",
    team: "1 developers",
    role: "Developer",
    challenges: [
      "Data-driven marketing strategies",
      "Real-time analytics implementation",
      "Personalized user experiences",
    ],
    achievements: ["Achieved 500K+ impressions", "Increased conversion rates by 250%", "Generated 15K+ leads"],
    links: {
      live: "https://ngl.cengage.com",
    },
  },
  {
    id: 12,
    title: "Gal's Best Pal",
    shortTitle: "GBP Wordpress Theme",
    description: "Custom Wordpress theme for Gal's Best Pal",
    detailedDescription:
      "Developed a custom Wordpress theme for Gal's Best Pal, focusing on performance optimization, SEO, and user engagement. Implemented custom plugins for enhanced functionality and user experience.",
    technologies: ["Wordpress", "HTML", "CSS", "Sass", "PHP", "JavaScript"],
    type: "WORDPRESS_THEME",
    status: "PRODUCTION",
    icon: Database,
    color: "cyan",
    year: "2022",
    duration: "6 months",
    team: "2 developers",
    role: "Lead Developer",
    challenges: ["Custom theme development", "Performance optimization", "SEO enhancements"],
    achievements: [
      "Improved page load time by 50%",
      "Increased organic traffic by 40%",
      "Achieved top rankings for target keywords",
    ],
    links: {
      live: "https://galsbestpal.com",
    },
  },
  {
    id: 13,
    title: "React Magma Component Library",
    shortTitle: "React Component Library",
    description: "Reusable React components for web applications",
    detailedDescription:
      "Developed a comprehensive React component library with reusable components, focusing on performance, accessibility, and developer experience. Implemented automated testing and documentation generation.",
    technologies: ["React", "Gatsby", "Jest", "React Testing Library", "Lerna", "Netlify"],
    type: "REACT_COMPONENT_LIBRARY",
    status: "COMPLETED",
    icon: Rocket,
    color: "orange",
    year: "2020",
    duration: "12 months",
    team: "5 developers",
    role: "Senior Frontend Engineer",
    challenges: ["Component reusability", "Performance optimization", "Accessibility compliance"],
    achievements: [
      "Over 40 reusable components",
      "Reduced development time by 30%",
      "Improved accessibility compliance to WCAG 2.1 standards",
    ],
    links: {
      live: "https://react-magma.cengage.com",
    },
  },
  {
    id: 14,
    title: "LeanBiologix Site Update",
    shortTitle: "LeanBiologix",
    description: "LeanBiologix wordpress site theme update",
    detailedDescription:
      "Updated the LeanBiologix Wordpress site with a new theme, focusing on performance, SEO, and user engagement. Implemented custom plugins for enhanced functionality and user experience.",
    technologies: ["Wordpress", "HTML", "CSS", "JavaScript", "PostgreSQL", "Docker"],
    type: "WORDPRESS_SITE_UPDATE",
    status: "COMPLETED",
    icon: Zap,
    color: "cyan",
    year: "2020",
    duration: "4 months",
    team: "2 developers",
    role: "Lead Developer",
    challenges: ["Theme customization", "Performance optimization", "SEO enhancements"],
    achievements: [
      "Improved page load time by 60%",
      "Increased organic traffic by 50%",
      "Achieved top rankings for target keywords",
    ],
    links: {
      live: "https://leanbiologix.com",
    },
  },
  {
    id: 15,
    title: "NGL Mindtap Schools",
    shortTitle: "NGL Mindtap Schools LMS",
    description: "National Geographic Learning Mindtap Schools LMS",
    detailedDescription:
      "Developed a comprehensive Learning Management System (LMS) for National Geographic Learning, focusing on user experience, performance, and security. Implemented advanced analytics and reporting features for educators.",
    technologies: ["React", "React Bootstrap", "JavaScript", "TypeScript", "Jest", "Enzyme", "Jenkins", "AWS"],
    type: "LMS_PLATFORM",
    status: "PRODUCTION",
    icon: Shield,
    color: "orange",
    year: "2021",
    duration: "24 months",
    team: "7 developers",
    role: "Frontend Tech Lead",
    challenges: [
      "Complex user interface design",
      "Performance optimization for large datasets",
      "Security compliance",
    ],
    achievements: ["Served 1M+ students", "Achieved 99.9% uptime", "Improved user satisfaction by 30%"],
    links: {
      live: "https://nglsync.cengage.com",
    },
  },
  {
    id: 16,
    title: "MyELT English Language Learning Management System",
    shortTitle: "LMS",
    description: "Educational platform for English language learning",
    detailedDescription:
      "Developed an educational platform for English language learning with personalized learning paths, interactive content, and real-time collaboration features. Integrated AI-powered tutoring and analytics for educators.",
    technologies: ["Java", "Angular", "React", "Struts", "CSS", "JavaScript", "Styled Components"],
    type: "EDUCATION_PLATFORM",
    status: "PRODUCTION",
    icon: Code,
    color: "cyan",
    year: "2017",
    duration: "60 months",
    team: "8 developers",
    role: "Senior Full-Stack Engineer",
    challenges: [
      "Personalized learning path algorithms",
      "Real-time collaboration features",
      "Speech Recognition tutoring integration",
      "Scalability for large user base",
    ],
    achievements: [
      "Served 5M+ students",
      "Achieved 99.9% real-time collaboration accuracy",
      "Improved learning outcomes by 40%",
    ],
    links: {
      live: "https://myelt.heinle.com/ilrn/authentication/signIn.do?inst=MYELT",
    },
  },
  {
    id: 17,
    title: "Resume Tailor Dev",
    shortTitle: "Resume Tailor",
    description: "Resume tailoring tool for job seekers",
    detailedDescription:
      "Developed a resume tailoring tool that helps job seekers create customized resumes for specific job applications, increasing their chances of landing interviews. The tool provides AI-powered suggestions and formatting options.",
    technologies: ["React", "NextJS", "Tailwind CSS", "TypeScript", "Shadcn/ui"],
    type: "CAREER_TOOL",
    status: "PRODUCTION",
    icon: Code,
    color: "orange",
    year: "2026",
    duration: "1 week",
    team: "1 developer",
    role: "Sole Developer",
    challenges: ["AI integration for resume suggestions", "User-friendly interface design", "Ensuring data privacy and security"],
    achievements: ["Launched to public with positive user feedback", "Helped users create tailored resumes for job applications"],
    links: {
      live: "https://tailor-dev-lilac.vercel.app",
    },
  },
  {
    id: 18,
    title: "Servicedesk IT Management Tool",
    shortTitle: "Servicedesk",
    description: "IT management tool for streamlining support processes",
    detailedDescription:
      "Developed an IT management tool that helps organizations streamline their IT support processes, improve response times, and enhance overall service quality.",
    technologies: ["React", "NextJS", "Tailwind CSS", "TypeScript", "Shadcn/ui", "Drizzle ORM", "PostgreSQL", "Vercel"],
    type: "IT_MANAGEMENT_TOOL",
    status: "PRODUCTION",
    icon: Code,
    color: "cyan",
    year: "2026",
    duration: "1 week",
    team: "1 developer",
    role: "Sole Developer",
    challenges: ["Complex IT support workflows", "Database optimization for performance", "User-friendly interface design"],
    achievements: ["Successfully launched the tool with positive user feedback", "Improved IT support response times for organizations using the tool"],
    links: {
      demo: "https://ticketing-system-vert-three.vercel.app",
      live: "https://greenervigil.gumroad.com/l/xpjvhb"
    },
  },
  {
    id: 19,
    title: "Proteus UI Component Library",
    shortTitle: "Proteus",
    description: "A comprehensive UI component library for modern web applications",
    detailedDescription:
      "Developed a robust UI component library that provides developers with a set of reusable, accessible, and customizable components for building modern web applications.",
    technologies: ["Web Components", "TypeScript", "Storybook", "CSS Variables", "Vite", "Vercel"],
    type: "UI_COMPONENT_LIBRARY",
    status: "PRODUCTION",
    icon: Code,
    color: "orange",
    year: "2026",
    duration: "2 weeks",
    team: "1 developer",
    role: "Sole Developer",
    challenges: ["Ensuring accessibility compliance", "Maintaining consistent design language", "Optimizing performance for large-scale applications"],
    achievements: [],
    links: {
      demo: "https://proteus-ui-storybook-ten.vercel.app/",
      live: "https://proteus-ui-docs.vercel.app"
    },
  }
]

const state: UserType = {
  name: 'Daniel Greener-Vigil',
  title: `Software Engineer | Tech Lead | Mentor`,
  aboutText: `<p>With over ${new Date().getFullYear() - 2014} years of experience as a Software Engineer, I am driven by a deep passion for learning and a commitment to continuous improvement. This passion fuels everything I do—whether it's tackling new technologies, leading teams through complex challenges, or mentoring the next generation of developers. I thrive in environments where innovation meets collaboration, and I am always eager to take on new challenges that push both my skills and my team’s abilities to new heights.</p>
  <p>Throughout my career, I've had the opportunity to work on a broad range of projects, leveraging a diverse set of technologies, including:</p></br>
  <ul class="about-list">
    <li><strong>Frontend:</strong> HTML, CSS, JavaScript, TypeScript, React React Native, Next.JS, Svelte, SolidJS, Tailwind, Bootstrap, Material UI, NPM, Yarn, PNPM, Turborepo, Storybook.</li>
    <li><strong>Backend:</strong> Node.js, Express, Java, Spring Boot, GraphQL, RESTful APIs, Prisma, PostgreSQL, MySQL, Redux.</li>
    <li><strong>Testing:</strong> Jest, React Testing Library, Enzyme, JUnit, Mockito.</li>
    <li><strong>DevOps:</strong> Docker, Kubernetes, Jenkins, GitHub Actions, Azure, Heroku, Netlify, Vercel.</li>
    </ul></br>
    <p>As a Tech Lead, I take pride in not only solving complex technical problems but also in building high-performing, cohesive teams. I believe in creating environments where people feel empowered to share ideas, learn from each other, and push the boundaries of what's possible. My approach is hands-on and collaborative, ensuring that both the code and the people behind it are always moving forward.</p>`,
  greenfield: '<p>In addition to my engineering work, I lead GreenField Development, a freelance partnership I founded to help self-taught developers accelerate their careers. Through this mentorship program, I focus on developing practical, project-based skills with a strong emphasis on Agile methodologies, version control practices, and project management. It’s incredibly rewarding to guide developers through their journeys and watch them grow into confident, capable contributors.</p>',
  projects,
  testimonials,
}

export { state }
