import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="py-6">
      <Head>
        <title>Daniel Greener Vigil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-16 h-full w-auto flex flex-col justify-center items-center">
        <h1 className={styles.title}>
          Daniel Greener- Vigil
        </h1>

        <p className={styles.description}>
          Software Engineer / Mentor
        </p>

        <div className={styles.grid}>
          <Link href='/about'>
            <a className={styles.card}>
              <h2>About &rarr;</h2>
            </a>
          </Link>

          <Link href='/projects'>
            <a className={styles.card}>
              <h2>Projects &rarr;</h2>
            </a>
          </Link>

          <Link href='/mentorship'>
            <a className={styles.card}>
              <h2>Mentorship &rarr;</h2>
            </a>
          </Link>

          <Link href='/contact'>
            <a className={styles.card}>
              <h2>Contact &rarr;</h2>
            </a>
          </Link>
        </div>
      </main>

      <footer className="flex justify-center align-baseline border-t">
        <p className="m-3">Greener-Vigil &copy; {new Date().getFullYear()}</p>
      </footer>
    </div>
  )
}

export default Home
